<?php
/**
 * @var $view System_View
 */
$employees = $view->getParam('all');
$limit = $view->getParam('limit');
$departments = $view->getParam('departments');
$selectValues = [2, 4, 6];
$url = rtrim($_SERVER['REQUEST_URI'], '/\\');
$urlArr = explode('/', $url);
if (is_numeric(end($urlArr))){
    array_pop($urlArr);
}
$url = implode('/', $urlArr);
?>
<h1>Сотрудники</h1>
<form action="<?= $url ?>" id="select-menu-form" method="post">
    <select name="select-department">
        <?php foreach ($departments as $department): ?>
            <option value="<?= $department->slug ?>"<?= in_array($department->slug, $urlArr) ? ' selected ' : '' ?>><?= $department->name ?></option>
        <?php endforeach; ?>
    </select>
    <select name="select-limit">
        <?php foreach ($selectValues as $value): ?>
            <option value="<?= $value ?>"<?= $value == $limit ? ' selected ' : '' ?>><?= $value ?></option>
        <?php endforeach; ?>
    </select>
</form>
<?php if(!empty($employees)): ?>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>Отдел</th>
        <th>ЗП</th>
        <th>Тип ЗП</th>
        <th>Должность</th>
        <th>День рождения</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($employees as $employee): ?>
        <tr>
            <td><?= $employee->id; ?></td>
            <td><?= $employee->firstname; ?></td>
            <td><?= $employee->lastname; ?></td>
            <td><?= $employee->middlename; ?></td>
            <td><?= $employee->department_name; ?></td>
            <td><?= $employee->salary; ?></td>
            <td><?= $employee->salary_type; ?></td>
            <td><?= $employee->position; ?></td>
            <td><?= $employee->birthday; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
<?php
$count_pages = ceil($view->getParam('count') / $limit);
$active  = $view->getParam('activePage');
$count_show_pages = 10;
$url_page = $url . '/';
if ($count_pages > 1):
    $left = $active - 1;
    $right = $count_pages - $active;
    if ($left < floor($count_show_pages / 2)) $start = 1;
    else $start = $active - floor($count_show_pages / 2);
    $end = $start + $count_show_pages - 1;
    if ($end > $count_pages) {
        $start -= ($end - $count_pages);
        $end = $count_pages;
        if ($start < 1) $start = 1;
    }
    ?>
    <div id="pagination">
        <?php if ($active != 1) { ?>
            <a href="<?=$url?>" title="Первая страница">&lt;&lt;&lt;</a>
            <a href="<?php if ($active == 2) { ?><?=$url?><?php } else { ?><?=$url_page.($active - 1)?><?php } ?>" title="Предыдущая страница">&lt;</a>
        <?php } ?>
        <?php for ($i = $start; $i <= $end; $i++) { ?>
            <?php if ($i == $active) { ?><span><?=$i?></span><?php } else { ?><a href="<?php if ($i == 1) { ?><?=$url?><?php } else { ?><?=$url_page.$i?><?php } ?>"><?=$i?></a><?php } ?>
        <?php } ?>
        <?php if ($active != $count_pages) { ?>
            <a href="<?=$url_page.($active + 1)?>" title="Следующая страница">&gt;</a>
            <a href="<?=$url_page.$count_pages?>" title="Последняя страница">&gt;&gt;&gt;</a>
        <?php } ?>
    </div>
<?php endif; ?>
