<?php
/**
 * @var $view System_View
 */
$employees = $view->getParam('all');
?>
<h1>Сотрудники</h1>
<?php if(!empty($employees)): ?>
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Отчество</th>
            <th>Отдел</th>
            <th>ЗП</th>
            <th>Тип ЗП</th>
            <th>Должность</th>
            <th>День рождения</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($employees as $employee): ?>
            <tr>
                <td><?= $employee->id; ?></td>
                <td><?= $employee->firstname; ?></td>
                <td><?= $employee->lastname; ?></td>
                <td><?= $employee->middlename; ?></td>
                <td><?= $employee->department_name; ?></td>
                <td><?= $employee->getSalary(); ?></td>
                <td><?= $employee->salary_type ? 'Ставка' : 'Почасово' ?></td>
                <td><?= $employee->position; ?></td>
                <td><?= $employee->birthday ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
