<!DOCTYPE html>
<html>
<head>
    <title>Employees</title>
    <link rel="stylesheet" text="text/css" href="/css/style.css?<?php echo time(); ?>">
    <meta charset="utf-8">
    <script type="text/javascript" src="/js/app.js?<?php echo time(); ?>"></script>
</head>
<body>
<div class="main-wrapper">
    <header>
        <div class="container">
            <div class="logo">
                <a href="/"><span class="mainlogo">Employees</span></a>
            </div>
            <menu id="mainmenu">
                <ul>
                    <li><a href="/">Главная </a></li>
                    <li><a href="/employee">Сотрудники из базы</a></li>
                    <li><a href="/employee/xml">Сотрудники из XML </a></li>
                </ul>
            </menu>
        </div>
    </header>
    <main class="container">
        <div class="content">
            <?php
            if (file_exists($contentFileName)) {
                include $contentFileName;
            }
            ?>
        </div>
    </main>
    <footer class="footer">
        <span>&copy; <a href="/">Employees</a> 2017. Created by Dmitry Skriplyonok.</span>
    </footer>
</div>
</body>
</html>